### 단체 생성 - 성공
POST http://localhost:8080/api/v1/organization
Content-Type: application/json
X-ACCOUNT-ID: 1

{
  "name": "Organization"
}

### 단체 생성 - 파라미터 검증 실패
POST http://localhost:8080/api/v1/organization
Content-Type: application/json
X-ACCOUNT-ID: 1

{
  "name": ""
}

### 단체 조회 - 성공
GET http://localhost:8080/api/v1/organization/1
Content-Type: application/json
